
import type { PeriodicElement } from '../types';

export const elements: PeriodicElement[] = [
  {
    "name": "Hydrogen",
    "symbol": "H",
    "number": 1,
    "atomic_mass": 1.008,
    "category": "diatomic nonmetal",
    "density": 0.08988,
    "melt": 13.99,
    "boil": 20.271,
    "electron_configuration_semantic": "1s1",
    "summary": "Hydrogen is the chemical element with the symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element on the periodic table.",
    "xpos": 1,
    "ypos": 1
  },
  {
    "name": "Helium",
    "symbol": "He",
    "number": 2,
    "atomic_mass": 4.002602,
    "category": "noble gas",
    "density": 0.1786,
    "melt": null,
    "boil": 4.224,
    "electron_configuration_semantic": "1s2",
    "summary": "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table.",
    "xpos": 18,
    "ypos": 1
  },
  {
    "name": "Lithium",
    "symbol": "Li",
    "number": 3,
    "atomic_mass": 6.94,
    "category": "alkali metal",
    "density": 0.534,
    "melt": 453.65,
    "boil": 1615,
    "electron_configuration_semantic": "[He] 2s1",
    "summary": "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal.",
    "xpos": 1,
    "ypos": 2
  },
  {
    "name": "Beryllium",
    "symbol": "Be",
    "number": 4,
    "atomic_mass": 9.0121831,
    "category": "alkaline earth metal",
    "density": 1.85,
    "melt": 1560,
    "boil": 2742,
    "electron_configuration_semantic": "[He] 2s2",
    "summary": "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.",
    "xpos": 2,
    "ypos": 2
  },
  {
    "name": "Boron",
    "symbol": "B",
    "number": 5,
    "atomic_mass": 10.81,
    "category": "metalloid",
    "density": 2.34,
    "melt": 2349,
    "boil": 4200,
    "electron_configuration_semantic": "[He] 2s2 2p1",
    "summary": "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust.",
    "xpos": 13,
    "ypos": 2
  },
  {
    "name": "Carbon",
    "symbol": "C",
    "number": 6,
    "atomic_mass": 12.011,
    "category": "polyatomic nonmetal",
    "density": 2.267,
    "melt": 3800,
    "boil": 5100,
    "electron_configuration_semantic": "[He] 2s2 2p2",
    "summary": "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
    "xpos": 14,
    "ypos": 2
  },
  {
    "name": "Nitrogen",
    "symbol": "N",
    "number": 7,
    "atomic_mass": 14.007,
    "category": "diatomic nonmetal",
    "density": 1.251,
    "melt": 63.15,
    "boil": 77.355,
    "electron_configuration_semantic": "[He] 2s2 2p3",
    "summary": "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.",
    "xpos": 15,
    "ypos": 2
  },
  {
    "name": "Oxygen",
    "symbol": "O",
    "number": 8,
    "atomic_mass": 15.999,
    "category": "diatomic nonmetal",
    "density": 1.429,
    "melt": 54.36,
    "boil": 90.188,
    "electron_configuration_semantic": "[He] 2s2 2p4",
    "summary": "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table and is a highly reactive nonmetal and oxidizing agent that readily forms oxides with most elements as well as with other compounds.",
    "xpos": 16,
    "ypos": 2
  },
  {
    "name": "Fluorine",
    "symbol": "F",
    "number": 9,
    "atomic_mass": 18.998403163,
    "category": "diatomic nonmetal",
    "density": 1.696,
    "melt": 53.48,
    "boil": 85.03,
    "electron_configuration_semantic": "[He] 2s2 2p5",
    "summary": "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions.",
    "xpos": 17,
    "ypos": 2
  },
  {
    "name": "Neon",
    "symbol": "Ne",
    "number": 10,
    "atomic_mass": 20.1797,
    "category": "noble gas",
    "density": 0.9002,
    "melt": 24.56,
    "boil": 27.104,
    "electron_configuration_semantic": "[He] 2s2 2p6",
    "summary": "Neon is a chemical element with symbol Ne and atomic number 10. It is in group 18 (noble gases) of the periodic table.",
    "xpos": 18,
    "ypos": 2
  },
  {
    "name": "Sodium",
    "symbol": "Na",
    "number": 11,
    "atomic_mass": 22.98976928,
    "category": "alkali metal",
    "density": 0.971,
    "melt": 370.944,
    "boil": 1156.09,
    "electron_configuration_semantic": "[Ne] 3s1",
    "summary": "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal.",
    "xpos": 1,
    "ypos": 3
  },
  {
    "name": "Magnesium",
    "symbol": "Mg",
    "number": 12,
    "atomic_mass": 24.305,
    "category": "alkaline earth metal",
    "density": 1.738,
    "melt": 923,
    "boil": 1363,
    "electron_configuration_semantic": "[Ne] 3s2",
    "summary": "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (Group 2, or alkaline earth metals) of the periodic table.",
    "xpos": 2,
    "ypos": 3
  },
  {
    "name": "Aluminium",
    "symbol": "Al",
    "number": 13,
    "atomic_mass": 26.9815385,
    "category": "post-transition metal",
    "density": 2.7,
    "melt": 933.47,
    "boil": 2792,
    "electron_configuration_semantic": "[Ne] 3s2 3p1",
    "summary": "Aluminium is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, non-magnetic and ductile metal in the boron group.",
    "xpos": 13,
    "ypos": 3
  },
  {
    "name": "Silicon",
    "symbol": "Si",
    "number": 14,
    "atomic_mass": 28.085,
    "category": "metalloid",
    "density": 2.329,
    "melt": 1687,
    "boil": 3538,
    "electron_configuration_semantic": "[Ne] 3s2 3p2",
    "summary": "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-grey metallic lustre, and it is a tetravalent metalloid and semiconductor.",
    "xpos": 14,
    "ypos": 3
  },
  {
    "name": "Phosphorus",
    "symbol": "P",
    "number": 15,
    "atomic_mass": 30.973761998,
    "category": "polyatomic nonmetal",
    "density": 1.82,
    "melt": 317.3,
    "boil": 553.7,
    "electron_configuration_semantic": "[Ne] 3s2 3p3",
    "summary": "Phosphorus is a chemical element with symbol P and atomic number 15. As an element, phosphorus exists in two major forms—white phosphorus and red phosphorus—but because it is highly reactive, phosphorus is never found as a free element on Earth.",
    "xpos": 15,
    "ypos": 3
  },
  {
    "name": "Sulfur",
    "symbol": "S",
    "number": 16,
    "atomic_mass": 32.06,
    "category": "polyatomic nonmetal",
    "density": 2.07,
    "melt": 388.36,
    "boil": 717.8,
    "electron_configuration_semantic": "[Ne] 3s2 3p4",
    "summary": "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent and nonmetallic.",
    "xpos": 16,
    "ypos": 3
  },
  {
    "name": "Chlorine",
    "symbol": "Cl",
    "number": 17,
    "atomic_mass": 35.45,
    "category": "diatomic nonmetal",
    "density": 3.214,
    "melt": 171.6,
    "boil": 239.11,
    "electron_configuration_semantic": "[Ne] 3s2 3p5",
    "summary": "Chlorine is a chemical element with symbol Cl and atomic number 17. The second-lightest of the halogens, it appears between fluorine and bromine in the periodic table and its properties are mostly intermediate between them.",
    "xpos": 17,
    "ypos": 3
  },
  {
    "name": "Argon",
    "symbol": "Ar",
    "number": 18,
    "atomic_mass": 39.948,
    "category": "noble gas",
    "density": 1.784,
    "melt": 83.81,
    "boil": 87.302,
    "electron_configuration_semantic": "[Ne] 3s2 3p6",
    "summary": "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas.",
    "xpos": 18,
    "ypos": 3
  },
  {
    "name": "Potassium",
    "symbol": "K",
    "number": 19,
    "atomic_mass": 39.0983,
    "category": "alkali metal",
    "density": 0.862,
    "melt": 336.7,
    "boil": 1032,
    "electron_configuration_semantic": "[Ar] 4s1",
    "summary": "Potassium is a chemical element with symbol K and atomic number 19. It is a silvery-white metal that is soft enough to be cut with a knife with little force.",
    "xpos": 1,
    "ypos": 4
  },
  {
    "name": "Calcium",
    "symbol": "Ca",
    "number": 20,
    "atomic_mass": 40.078,
    "category": "alkaline earth metal",
    "density": 1.55,
    "melt": 1115,
    "boil": 1757,
    "electron_configuration_semantic": "[Ar] 4s2",
    "summary": "Calcium is a chemical element with symbol Ca and atomic number 20. As an alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air.",
    "xpos": 2,
    "ypos": 4
  },
  {
    "name": "Scandium",
    "symbol": "Sc",
    "number": 21,
    "atomic_mass": 44.955908,
    "category": "transition metal",
    "density": 2.985,
    "melt": 1814,
    "boil": 3109,
    "electron_configuration_semantic": "[Ar] 3d1 4s2",
    "summary": "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been sometimes classified as a rare-earth element, along with yttrium and the lanthanides.",
    "xpos": 3,
    "ypos": 4
  },
  {
    "name": "Titanium",
    "symbol": "Ti",
    "number": 22,
    "atomic_mass": 47.867,
    "category": "transition metal",
    "density": 4.506,
    "melt": 1941,
    "boil": 3560,
    "electron_configuration_semantic": "[Ar] 3d2 4s2",
    "summary": "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength.",
    "xpos": 4,
    "ypos": 4
  },
  {
    "name": "Vanadium",
    "symbol": "V",
    "number": 23,
    "atomic_mass": 50.9415,
    "category": "transition metal",
    "density": 6.11,
    "melt": 2183,
    "boil": 3680,
    "electron_configuration_semantic": "[Ar] 3d3 4s2",
    "summary": "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery grey, ductile, and malleable transition metal.",
    "xpos": 5,
    "ypos": 4
  },
  {
    "name": "Chromium",
    "symbol": "Cr",
    "number": 24,
    "atomic_mass": 51.9961,
    "category": "transition metal",
    "density": 7.19,
    "melt": 2180,
    "boil": 2944,
    "electron_configuration_semantic": "[Ar] 3d5 4s1",
    "summary": "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in Group 6.",
    "xpos": 6,
    "ypos": 4
  },
  {
    "name": "Manganese",
    "symbol": "Mn",
    "number": 25,
    "atomic_mass": 54.938044,
    "category": "transition metal",
    "density": 7.21,
    "melt": 1519,
    "boil": 2334,
    "electron_configuration_semantic": "[Ar] 3d5 4s2",
    "summary": "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron.",
    "xpos": 7,
    "ypos": 4
  },
  {
    "name": "Iron",
    "symbol": "Fe",
    "number": 26,
    "atomic_mass": 55.845,
    "category": "transition metal",
    "density": 7.874,
    "melt": 1811,
    "boil": 3134,
    "electron_configuration_semantic": "[Ar] 3d6 4s2",
    "summary": "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal in the first transition series.",
    "xpos": 8,
    "ypos": 4
  },
  {
    "name": "Cobalt",
    "symbol": "Co",
    "number": 27,
    "atomic_mass": 58.933194,
    "category": "transition metal",
    "density": 8.9,
    "melt": 1768,
    "boil": 3200,
    "electron_configuration_semantic": "[Ar] 3d7 4s2",
    "summary": "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt is found in the Earth's crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron.",
    "xpos": 9,
    "ypos": 4
  },
  {
    "name": "Nickel",
    "symbol": "Ni",
    "number": 28,
    "atomic_mass": 58.6934,
    "category": "transition metal",
    "density": 8.908,
    "melt": 1728,
    "boil": 3186,
    "electron_configuration_semantic": "[Ar] 3d8 4s2",
    "summary": "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge.",
    "xpos": 10,
    "ypos": 4
  },
  {
    "name": "Copper",
    "symbol": "Cu",
    "number": 29,
    "atomic_mass": 63.546,
    "category": "transition metal",
    "density": 8.96,
    "melt": 1357.77,
    "boil": 2835,
    "electron_configuration_semantic": "[Ar] 3d10 4s1",
    "summary": "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity.",
    "xpos": 11,
    "ypos": 4
  },
  {
    "name": "Zinc",
    "symbol": "Zn",
    "number": 30,
    "atomic_mass": 65.38,
    "category": "transition metal",
    "density": 7.14,
    "melt": 692.68,
    "boil": 1180,
    "electron_configuration_semantic": "[Ar] 3d10 4s2",
    "summary": "Zinc, in commerce also spelter, is a chemical element with symbol Zn and atomic number 30. It is the first element in group 12 of the periodic table.",
    "xpos": 12,
    "ypos": 4
  },
  {
    "name": "Gallium",
    "symbol": "Ga",
    "number": 31,
    "atomic_mass": 69.723,
    "category": "post-transition metal",
    "density": 5.91,
    "melt": 302.9146,
    "boil": 2673,
    "electron_configuration_semantic": "[Ar] 3d10 4s2 4p1",
    "summary": "Gallium is a chemical element with symbol Ga and atomic number 31. Elemental gallium does not occur in free form in nature, but as gallium(III) compounds that are in trace amounts in zinc ores and in bauxite.",
    "xpos": 13,
    "ypos": 4
  },
  {
    "name": "Germanium",
    "symbol": "Ge",
    "number": 32,
    "atomic_mass": 72.63,
    "category": "metalloid",
    "density": 5.323,
    "melt": 1211.4,
    "boil": 3106,
    "electron_configuration_semantic": "[Ar] 3d10 4s2 4p2",
    "summary": "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group, chemically similar to its group neighbors tin and silicon.",
    "xpos": 14,
    "ypos": 4
  },
  {
    "name": "Arsenic",
    "symbol": "As",
    "number": 33,
    "atomic_mass": 74.921595,
    "category": "metalloid",
    "density": 5.727,
    "melt": 1090,
    "boil": 887,
    "electron_configuration_semantic": "[Ar] 3d10 4s2 4p3",
    "summary": "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal.",
    "xpos": 15,
    "ypos": 4
  },
  {
    "name": "Selenium",
    "symbol": "Se",
    "number": 34,
    "atomic_mass": 78.971,
    "category": "polyatomic nonmetal",
    "density": 4.81,
    "melt": 494,
    "boil": 958,
    "electron_configuration_semantic": "[Ar] 3d10 4s2 4p4",
    "summary": "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium, and also has similarities to arsenic.",
    "xpos": 16,
    "ypos": 4
  },
  {
    "name": "Bromine",
    "symbol": "Br",
    "number": 35,
    "atomic_mass": 79.904,
    "category": "diatomic nonmetal",
    "density": 3.1028,
    "melt": 265.8,
    "boil": 332,
    "electron_configuration_semantic": "[Ar] 3d10 4s2 4p5",
    "summary": "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas.",
    "xpos": 17,
    "ypos": 4
  },
  {
    "name": "Krypton",
    "symbol": "Kr",
    "number": 36,
    "atomic_mass": 83.798,
    "category": "noble gas",
    "density": 3.749,
    "melt": 115.78,
    "boil": 119.93,
    "electron_configuration_semantic": "[Ar] 3d10 4s2 4p6",
    "summary": "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements.",
    "xpos": 18,
    "ypos": 4
  },
  {
    "name": "Rubidium",
    "symbol": "Rb",
    "number": 37,
    "atomic_mass": 85.4678,
    "category": "alkali metal",
    "density": 1.532,
    "melt": 312.45,
    "boil": 961,
    "electron_configuration_semantic": "[Kr] 5s1",
    "summary": "Rubidium is a chemical element with symbol Rb and atomic number 37. It is a very soft, silvery-white metal in the alkali metal group.",
    "xpos": 1,
    "ypos": 5
  },
  {
    "name": "Strontium",
    "symbol": "Sr",
    "number": 38,
    "atomic_mass": 87.62,
    "category": "alkaline earth metal",
    "density": 2.64,
    "melt": 1050,
    "boil": 1655,
    "electron_configuration_semantic": "[Kr] 5s2",
    "summary": "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly reactive chemically.",
    "xpos": 2,
    "ypos": 5
  },
  {
    "name": "Yttrium",
    "symbol": "Y",
    "number": 39,
    "atomic_mass": 88.90584,
    "category": "transition metal",
    "density": 4.472,
    "melt": 1799,
    "boil": 3609,
    "electron_configuration_semantic": "[Kr] 4d1 5s2",
    "summary": "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a 'rare-earth element'.",
    "xpos": 3,
    "ypos": 5
  },
  {
    "name": "Zirconium",
    "symbol": "Zr",
    "number": 40,
    "atomic_mass": 91.224,
    "category": "transition metal",
    "density": 6.52,
    "melt": 2128,
    "boil": 4682,
    "electron_configuration_semantic": "[Kr] 4d2 5s2",
    "summary": "Zirconium is a chemical element with symbol Zr and atomic number 40. The name of zirconium is taken from the name of the mineral zircon, the most important source of zirconium.",
    "xpos": 4,
    "ypos": 5
  },
  {
    "name": "Niobium",
    "symbol": "Nb",
    "number": 41,
    "atomic_mass": 92.90637,
    "category": "transition metal",
    "density": 8.57,
    "melt": 2750,
    "boil": 5017,
    "electron_configuration_semantic": "[Kr] 4d4 5s1",
    "summary": "Niobium, formerly columbium, is a chemical element with symbol Nb and atomic number 41. It is a soft, grey, ductile transition metal, which is often found in the pyrochlore mineral, the main commercial source for niobium, and columbite.",
    "xpos": 5,
    "ypos": 5
  },
  {
    "name": "Molybdenum",
    "symbol": "Mo",
    "number": 42,
    "atomic_mass": 95.95,
    "category": "transition metal",
    "density": 10.28,
    "melt": 2896,
    "boil": 4912,
    "electron_configuration_semantic": "[Kr] 4d5 5s1",
    "summary": "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead, since its ores were confused with lead ores.",
    "xpos": 6,
    "ypos": 5
  },
  {
    "name": "Technetium",
    "symbol": "Tc",
    "number": 43,
    "atomic_mass": 98,
    "category": "transition metal",
    "density": 11.5,
    "melt": 2430,
    "boil": 4538,
    "electron_configuration_semantic": "[Kr] 4d5 5s2",
    "summary": "Technetium is a chemical element with symbol Tc and atomic number 43. It is the lightest element of which all isotopes are radioactive, none of which are stable except for the fully ionized state of 97Tc.",
    "xpos": 7,
    "ypos": 5
  },
  {
    "name": "Ruthenium",
    "symbol": "Ru",
    "number": 44,
    "atomic_mass": 101.07,
    "category": "transition metal",
    "density": 12.41,
    "melt": 2607,
    "boil": 4423,
    "electron_configuration_semantic": "[Kr] 4d7 5s1",
    "summary": "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table.",
    "xpos": 8,
    "ypos": 5
  },
  {
    "name": "Rhodium",
    "symbol": "Rh",
    "number": 45,
    "atomic_mass": 102.9055,
    "category": "transition metal",
    "density": 12.41,
    "melt": 2237,
    "boil": 3968,
    "electron_configuration_semantic": "[Kr] 4d8 5s1",
    "summary": "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal.",
    "xpos": 9,
    "ypos": 5
  },
  {
    "name": "Palladium",
    "symbol": "Pd",
    "number": 46,
    "atomic_mass": 106.42,
    "category": "transition metal",
    "density": 12.023,
    "melt": 1828.05,
    "boil": 3236,
    "electron_configuration_semantic": "[Kr] 4d10",
    "summary": "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston.",
    "xpos": 10,
    "ypos": 5
  },
  {
    "name": "Silver",
    "symbol": "Ag",
    "number": 47,
    "atomic_mass": 107.8682,
    "category": "transition metal",
    "density": 10.49,
    "melt": 1234.93,
    "boil": 2435,
    "electron_configuration_semantic": "[Kr] 4d10 5s1",
    "summary": "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
    "xpos": 11,
    "ypos": 5
  },
  {
    "name": "Cadmium",
    "symbol": "Cd",
    "number": 48,
    "atomic_mass": 112.414,
    "category": "transition metal",
    "density": 8.65,
    "melt": 594.22,
    "boil": 1040,
    "electron_configuration_semantic": "[Kr] 4d10 5s2",
    "summary": "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury.",
    "xpos": 12,
    "ypos": 5
  },
  {
    "name": "Indium",
    "symbol": "In",
    "number": 49,
    "atomic_mass": 114.818,
    "category": "post-transition metal",
    "density": 7.31,
    "melt": 429.7485,
    "boil": 2345,
    "electron_configuration_semantic": "[Kr] 4d10 5s2 5p1",
    "summary": "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metal that makes up 0.21 parts per million of the Earth's crust.",
    "xpos": 13,
    "ypos": 5
  },
  {
    "name": "Tin",
    "symbol": "Sn",
    "number": 50,
    "atomic_mass": 118.71,
    "category": "post-transition metal",
    "density": 7.31,
    "melt": 505.08,
    "boil": 2875,
    "electron_configuration_semantic": "[Kr] 4d10 5s2 5p2",
    "summary": "Tin is a chemical element with symbol Sn and atomic number 50. It is a post-transition metal in group 14 of the periodic table.",
    "xpos": 14,
    "ypos": 5
  },
  {
    "name": "Antimony",
    "symbol": "Sb",
    "number": 51,
    "atomic_mass": 121.76,
    "category": "metalloid",
    "density": 6.697,
    "melt": 903.78,
    "boil": 1860,
    "electron_configuration_semantic": "[Kr] 4d10 5s2 5p3",
    "summary": "Antimony is a chemical element with symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3).",
    "xpos": 15,
    "ypos": 5
  },
  {
    "name": "Tellurium",
    "symbol": "Te",
    "number": 52,
    "atomic_mass": 127.6,
    "category": "metalloid",
    "density": 6.24,
    "melt": 722.66,
    "boil": 1261,
    "electron_configuration_semantic": "[Kr] 4d10 5s2 5p4",
    "summary": "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid.",
    "xpos": 16,
    "ypos": 5
  },
  {
    "name": "Iodine",
    "symbol": "I",
    "number": 53,
    "atomic_mass": 126.90447,
    "category": "diatomic nonmetal",
    "density": 4.933,
    "melt": 386.85,
    "boil": 457.4,
    "electron_configuration_semantic": "[Kr] 4d10 5s2 5p5",
    "summary": "Iodine is a chemical element with symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a lustrous, purple-black nonmetallic solid at standard conditions that sublimes readily to form a violet gas.",
    "xpos": 17,
    "ypos": 5
  },
  {
    "name": "Xenon",
    "symbol": "Xe",
    "number": 54,
    "atomic_mass": 131.293,
    "category": "noble gas",
    "density": 5.894,
    "melt": 161.4,
    "boil": 165.051,
    "electron_configuration_semantic": "[Kr] 4d10 5s2 5p6",
    "summary": "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts.",
    "xpos": 18,
    "ypos": 5
  },
  {
    "name": "Cesium",
    "symbol": "Cs",
    "number": 55,
    "atomic_mass": 132.90545196,
    "category": "alkali metal",
    "density": 1.93,
    "melt": 301.7,
    "boil": 944,
    "electron_configuration_semantic": "[Xe] 6s1",
    "summary": "Caesium or cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-gold alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.",
    "xpos": 1,
    "ypos": 6
  },
  {
    "name": "Barium",
    "symbol": "Ba",
    "number": 56,
    "atomic_mass": 137.327,
    "category": "alkaline earth metal",
    "density": 3.51,
    "melt": 1000,
    "boil": 2170,
    "electron_configuration_semantic": "[Xe] 6s2",
    "summary": "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in Group 2 and is a soft, silvery alkaline earth metal.",
    "xpos": 2,
    "ypos": 6
  },
  {
    "name": "Lanthanum",
    "symbol": "La",
    "number": 57,
    "atomic_mass": 138.90547,
    "category": "lanthanide",
    "density": 6.146,
    "melt": 1193,
    "boil": 3737,
    "electron_configuration_semantic": "[Xe] 5d1 6s2",
    "summary": "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes rapidly when exposed to air and is soft enough to be cut with a knife.",
    "xpos": 3,
    "ypos": 9
  },
  {
    "name": "Cerium",
    "symbol": "Ce",
    "number": 58,
    "atomic_mass": 140.116,
    "category": "lanthanide",
    "density": 6.77,
    "melt": 1068,
    "boil": 3716,
    "electron_configuration_semantic": "[Xe] 4f1 5d1 6s2",
    "summary": "Cerium is a chemical element with symbol Ce and atomic number 58. It is a soft, ductile and silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a knife.",
    "xpos": 4,
    "ypos": 9
  },
  {
    "name": "Praseodymium",
    "symbol": "Pr",
    "number": 59,
    "atomic_mass": 140.90766,
    "category": "lanthanide",
    "density": 6.77,
    "melt": 1208,
    "boil": 3793,
    "electron_configuration_semantic": "[Xe] 4f3 6s2",
    "summary": "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is the third member of the lanthanide series and is traditionally considered to be one of the rare-earth metals.",
    "xpos": 5,
    "ypos": 9
  },
  {
    "name": "Neodymium",
    "symbol": "Nd",
    "number": 60,
    "atomic_mass": 144.242,
    "category": "lanthanide",
    "density": 7.01,
    "melt": 1297,
    "boil": 3347,
    "electron_configuration_semantic": "[Xe] 4f4 6s2",
    "summary": "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a soft silvery metal that tarnishes in air.",
    "xpos": 6,
    "ypos": 9
  },
  {
    "name": "Promethium",
    "symbol": "Pm",
    "number": 61,
    "atomic_mass": 145,
    "category": "lanthanide",
    "density": 7.26,
    "melt": 1315,
    "boil": 3273,
    "electron_configuration_semantic": "[Xe] 4f5 6s2",
    "summary": "Promethium, a chemical element with the symbol Pm and atomic number 61, is one of only two radioactive elements that are followed in the periodic table by elements with stable forms, the other being technetium.",
    "xpos": 7,
    "ypos": 9
  },
  {
    "name": "Samarium",
    "symbol": "Sm",
    "number": 62,
    "atomic_mass": 150.36,
    "category": "lanthanide",
    "density": 7.52,
    "melt": 1345,
    "boil": 2067,
    "electron_configuration_semantic": "[Xe] 4f6 6s2",
    "summary": "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that slowly oxidizes in air.",
    "xpos": 8,
    "ypos": 9
  },
  {
    "name": "Europium",
    "symbol": "Eu",
    "number": 63,
    "atomic_mass": 151.964,
    "category": "lanthanide",
    "density": 5.244,
    "melt": 1099,
    "boil": 1802,
    "electron_configuration_semantic": "[Xe] 4f7 6s2",
    "summary": "Europium is a chemical element with symbol Eu and atomic number 63. It is a moderately hard, silvery metal which readily oxidizes in air and water.",
    "xpos": 9,
    "ypos": 9
  },
  {
    "name": "Gadolinium",
    "symbol": "Gd",
    "number": 64,
    "atomic_mass": 157.25,
    "category": "lanthanide",
    "density": 7.9,
    "melt": 1585,
    "boil": 3546,
    "electron_configuration_semantic": "[Xe] 4f7 5d1 6s2",
    "summary": "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is a silvery-white, malleable and ductile rare-earth metal.",
    "xpos": 10,
    "ypos": 9
  },
  {
    "name": "Terbium",
    "symbol": "Tb",
    "number": 65,
    "atomic_mass": 158.92535,
    "category": "lanthanide",
    "density": 8.23,
    "melt": 1629,
    "boil": 3503,
    "electron_configuration_semantic": "[Xe] 4f9 6s2",
    "summary": "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile and soft enough to be cut with a knife.",
    "xpos": 11,
    "ypos": 9
  },
  {
    "name": "Dysprosium",
    "symbol": "Dy",
    "number": 66,
    "atomic_mass": 162.5,
    "category": "lanthanide",
    "density": 8.54,
    "melt": 1680,
    "boil": 2840,
    "electron_configuration_semantic": "[Xe] 4f10 6s2",
    "summary": "Dysprosium is a chemical element with the symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster.",
    "xpos": 12,
    "ypos": 9
  },
  {
    "name": "Holmium",
    "symbol": "Ho",
    "number": 67,
    "atomic_mass": 164.93033,
    "category": "lanthanide",
    "density": 8.79,
    "melt": 1734,
    "boil": 2993,
    "electron_configuration_semantic": "[Xe] 4f11 6s2",
    "summary": "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare earth element.",
    "xpos": 13,
    "ypos": 9
  },
  {
    "name": "Erbium",
    "symbol": "Er",
    "number": 68,
    "atomic_mass": 167.259,
    "category": "lanthanide",
    "density": 9.066,
    "melt": 1802,
    "boil": 3141,
    "electron_configuration_semantic": "[Xe] 4f12 6s2",
    "summary": "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements on Earth.",
    "xpos": 14,
    "ypos": 9
  },
  {
    "name": "Thulium",
    "symbol": "Tm",
    "number": 69,
    "atomic_mass": 168.93422,
    "category": "lanthanide",
    "density": 9.32,
    "melt": 1818,
    "boil": 2223,
    "electron_configuration_semantic": "[Xe] 4f13 6s2",
    "summary": "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series.",
    "xpos": 15,
    "ypos": 9
  },
  {
    "name": "Ytterbium",
    "symbol": "Yb",
    "number": 70,
    "atomic_mass": 173.045,
    "category": "lanthanide",
    "density": 6.9,
    "melt": 1097,
    "boil": 1469,
    "electron_configuration_semantic": "[Xe] 4f14 6s2",
    "summary": "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state.",
    "xpos": 16,
    "ypos": 9
  },
  {
    "name": "Lutetium",
    "symbol": "Lu",
    "number": 71,
    "atomic_mass": 174.9668,
    "category": "lanthanide",
    "density": 9.841,
    "melt": 1925,
    "boil": 3675,
    "electron_configuration_semantic": "[Xe] 4f14 5d1 6s2",
    "summary": "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry, but not in moist air.",
    "xpos": 17,
    "ypos": 9
  },
  {
    "name": "Hafnium",
    "symbol": "Hf",
    "number": 72,
    "atomic_mass": 178.49,
    "category": "transition metal",
    "density": 13.31,
    "melt": 2506,
    "boil": 4876,
    "electron_configuration_semantic": "[Xe] 4f14 5d2 6s2",
    "summary": "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals.",
    "xpos": 4,
    "ypos": 6
  },
  {
    "name": "Tantalum",
    "symbol": "Ta",
    "number": 73,
    "atomic_mass": 180.94788,
    "category": "transition metal",
    "density": 16.69,
    "melt": 3290,
    "boil": 5731,
    "electron_configuration_semantic": "[Xe] 4f14 5d3 6s2",
    "summary": "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, its name is derived from Tantalus, an antagonist from Greek mythology.",
    "xpos": 5,
    "ypos": 6
  },
  {
    "name": "Tungsten",
    "symbol": "W",
    "number": 74,
    "atomic_mass": 183.84,
    "category": "transition metal",
    "density": 19.25,
    "melt": 3695,
    "boil": 5828,
    "electron_configuration_semantic": "[Xe] 4f14 5d4 6s2",
    "summary": "Tungsten, also known as wolfram, is a chemical element with symbol W and atomic number 74. The word tungsten comes from the Swedish language tung sten, which directly translates to heavy stone.",
    "xpos": 6,
    "ypos": 6
  },
  {
    "name": "Rhenium",
    "symbol": "Re",
    "number": 75,
    "atomic_mass": 186.207,
    "category": "transition metal",
    "density": 21.02,
    "melt": 3459,
    "boil": 5869,
    "electron_configuration_semantic": "[Xe] 4f14 5d5 6s2",
    "summary": "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-white, heavy, third-row transition metal in group 7 of the periodic table.",
    "xpos": 7,
    "ypos": 6
  },
  {
    "name": "Osmium",
    "symbol": "Os",
    "number": 76,
    "atomic_mass": 190.23,
    "category": "transition metal",
    "density": 22.59,
    "melt": 3306,
    "boil": 5285,
    "electron_configuration_semantic": "[Xe] 4f14 5d6 6s2",
    "summary": "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores.",
    "xpos": 8,
    "ypos": 6
  },
  {
    "name": "Iridium",
    "symbol": "Ir",
    "number": 77,
    "atomic_mass": 192.217,
    "category": "transition metal",
    "density": 22.56,
    "melt": 2719,
    "boil": 4701,
    "electron_configuration_semantic": "[Xe] 4f14 5d7 6s2",
    "summary": "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is the second-densest element (after osmium) and is the most corrosion-resistant metal, even at temperatures as high as 2000 °C.",
    "xpos": 9,
    "ypos": 6
  },
  {
    "name": "Platinum",
    "symbol": "Pt",
    "number": 78,
    "atomic_mass": 195.084,
    "category": "transition metal",
    "density": 21.45,
    "melt": 2041.4,
    "boil": 4098,
    "electron_configuration_semantic": "[Xe] 4f14 5d9 6s1",
    "summary": "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal.",
    "xpos": 10,
    "ypos": 6
  },
  {
    "name": "Gold",
    "symbol": "Au",
    "number": 79,
    "atomic_mass": 196.966569,
    "category": "transition metal",
    "density": 19.3,
    "melt": 1337.33,
    "boil": 3129,
    "electron_configuration_semantic": "[Xe] 4f14 5d10 6s1",
    "summary": "Gold is a chemical element with symbol Au and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.",
    "xpos": 11,
    "ypos": 6
  },
  {
    "name": "Mercury",
    "symbol": "Hg",
    "number": 80,
    "atomic_mass": 200.592,
    "category": "transition metal",
    "density": 13.534,
    "melt": 234.321,
    "boil": 629.88,
    "electron_configuration_semantic": "[Xe] 4f14 5d10 6s2",
    "summary": "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum.",
    "xpos": 12,
    "ypos": 6
  },
  {
    "name": "Thallium",
    "symbol": "Tl",
    "number": 81,
    "atomic_mass": 204.38,
    "category": "post-transition metal",
    "density": 11.85,
    "melt": 577,
    "boil": 1746,
    "electron_configuration_semantic": "[Xe] 4f14 5d10 6s2 6p1",
    "summary": "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature.",
    "xpos": 13,
    "ypos": 6
  },
  {
    "name": "Lead",
    "symbol": "Pb",
    "number": 82,
    "atomic_mass": 207.2,
    "category": "post-transition metal",
    "density": 11.34,
    "melt": 600.61,
    "boil": 2022,
    "electron_configuration_semantic": "[Xe] 4f14 5d10 6s2 6p2",
    "summary": "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials.",
    "xpos": 14,
    "ypos": 6
  },
  {
    "name": "Bismuth",
    "symbol": "Bi",
    "number": 83,
    "atomic_mass": 208.9804,
    "category": "post-transition metal",
    "density": 9.78,
    "melt": 544.7,
    "boil": 1837,
    "electron_configuration_semantic": "[Xe] 4f14 5d10 6s2 6p3",
    "summary": "Bismuth is a chemical element with symbol Bi and atomic number 83. It is a pentavalent post-transition metal and one of the pnictogens with chemical properties resembling its lighter homologs arsenic and antimony.",
    "xpos": 15,
    "ypos": 6
  },
  {
    "name": "Polonium",
    "symbol": "Po",
    "number": 84,
    "atomic_mass": 209,
    "category": "post-transition metal",
    "density": 9.196,
    "melt": 527,
    "boil": 1235,
    "electron_configuration_semantic": "[Xe] 4f14 5d10 6s2 6p4",
    "summary": "Polonium is a chemical element with symbol Po and atomic number 84, discovered in 1898 by Marie and Pierre Curie. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to bismuth and tellurium, and it occurs in uranium ores.",
    "xpos": 16,
    "ypos": 6
  },
  {
    "name": "Astatine",
    "symbol": "At",
    "number": 85,
    "atomic_mass": 210,
    "category": "metalloid",
    "density": 7,
    "melt": 575,
    "boil": 610,
    "electron_configuration_semantic": "[Xe] 4f14 5d10 6s2 6p5",
    "summary": "Astatine is a very rare radioactive chemical element with the chemical symbol At and atomic number 85. It occurs on Earth as the decay product of various heavier elements.",
    "xpos": 17,
    "ypos": 6
  },
  {
    "name": "Radon",
    "symbol": "Rn",
    "number": 86,
    "atomic_mass": 222,
    "category": "noble gas",
    "density": 9.73,
    "melt": 202,
    "boil": 211.5,
    "electron_configuration_semantic": "[Xe] 4f14 5d10 6s2 6p6",
    "summary": "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas.",
    "xpos": 18,
    "ypos": 6
  },
  {
    "name": "Francium",
    "symbol": "Fr",
    "number": 87,
    "atomic_mass": 223,
    "category": "alkali metal",
    "density": 1.87,
    "melt": 300,
    "boil": 950,
    "electron_configuration_semantic": "[Rn] 7s1",
    "summary": "Francium is a chemical element with symbol Fr and atomic number 87. It used to be known as eka-caesium and actinium K.",
    "xpos": 1,
    "ypos": 7
  },
  {
    "name": "Radium",
    "symbol": "Ra",
    "number": 88,
    "atomic_mass": 226,
    "category": "alkaline earth metal",
    "density": 5.5,
    "melt": 973,
    "boil": 2010,
    "electron_configuration_semantic": "[Rn] 7s2",
    "summary": "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals.",
    "xpos": 2,
    "ypos": 7
  },
  {
    "name": "Actinium",
    "symbol": "Ac",
    "number": 89,
    "atomic_mass": 227,
    "category": "actinide",
    "density": 10.07,
    "melt": 1323,
    "boil": 3471,
    "electron_configuration_semantic": "[Rn] 6d1 7s2",
    "summary": "Actinium is a radioactive chemical element with symbol Ac and atomic number 89, which was discovered in 1899. It was the first non-primordial radioactive element to be isolated.",
    "xpos": 3,
    "ypos": 10
  },
  {
    "name": "Thorium",
    "symbol": "Th",
    "number": 90,
    "atomic_mass": 232.0377,
    "category": "actinide",
    "density": 11.724,
    "melt": 2023,
    "boil": 5061,
    "electron_configuration_semantic": "[Rn] 6d2 7s2",
    "summary": "Thorium is a weakly radioactive metallic chemical element with symbol Th and atomic number 90. Thorium is silvery and tarnishes black when exposed to air, forming thorium dioxide; it is moderately soft, malleable, and has a high melting point.",
    "xpos": 4,
    "ypos": 10
  },
  {
    "name": "Protactinium",
    "symbol": "Pa",
    "number": 91,
    "atomic_mass": 231.03588,
    "category": "actinide",
    "density": 15.37,
    "melt": 1841,
    "boil": 4300,
    "electron_configuration_semantic": "[Rn] 5f2 6d1 7s2",
    "summary": "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids.",
    "xpos": 5,
    "ypos": 10
  },
  {
    "name": "Uranium",
    "symbol": "U",
    "number": 92,
    "atomic_mass": 238.02891,
    "category": "actinide",
    "density": 19.1,
    "melt": 1405.3,
    "boil": 4404,
    "electron_configuration_semantic": "[Rn] 5f3 6d1 7s2",
    "summary": "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-white metal in the actinide series of the periodic table.",
    "xpos": 6,
    "ypos": 10
  },
  {
    "name": "Neptunium",
    "symbol": "Np",
    "number": 93,
    "atomic_mass": 237,
    "category": "actinide",
    "density": 20.45,
    "melt": 917,
    "boil": 4273,
    "electron_configuration_semantic": "[Rn] 5f4 6d1 7s2",
    "summary": "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element.",
    "xpos": 7,
    "ypos": 10
  },
  {
    "name": "Plutonium",
    "symbol": "Pu",
    "number": 94,
    "atomic_mass": 244,
    "category": "actinide",
    "density": 19.816,
    "melt": 912.5,
    "boil": 3505,
    "electron_configuration_semantic": "[Rn] 5f6 7s2",
    "summary": "Plutonium is a transuranic radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized.",
    "xpos": 8,
    "ypos": 10
  },
  {
    "name": "Americium",
    "symbol": "Am",
    "number": 95,
    "atomic_mass": 243,
    "category": "actinide",
    "density": 13.67,
    "melt": 1449,
    "boil": 2880,
    "electron_configuration_semantic": "[Rn] 5f7 7s2",
    "summary": "Americium is a radioactive transuranic chemical element with symbol Am and atomic number 95. This member of the actinide series is located in the periodic table under the lanthanide element europium, and thus by analogy was named after the Americas.",
    "xpos": 9,
    "ypos": 10
  },
  {
    "name": "Curium",
    "symbol": "Cm",
    "number": 96,
    "atomic_mass": 247,
    "category": "actinide",
    "density": 13.51,
    "melt": 1613,
    "boil": 3383,
    "electron_configuration_semantic": "[Rn] 5f7 6d1 7s2",
    "summary": "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie – both were known for their research on radioactivity.",
    "xpos": 10,
    "ypos": 10
  },
  {
    "name": "Berkelium",
    "symbol": "Bk",
    "number": 97,
    "atomic_mass": 247,
    "category": "actinide",
    "density": 14.78,
    "melt": 1259,
    "boil": 2900,
    "electron_configuration_semantic": "[Rn] 5f9 7s2",
    "summary": "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series.",
    "xpos": 11,
    "ypos": 10
  },
  {
    "name": "Californium",
    "symbol": "Cf",
    "number": 98,
    "atomic_mass": 251,
    "category": "actinide",
    "density": 15.1,
    "melt": 1173,
    "boil": 1743,
    "electron_configuration_semantic": "[Rn] 5f10 7s2",
    "summary": "Californium is a radioactive metallic chemical element with symbol Cf and atomic number 98. The element was first made in 1950 at the University of California Radiation Laboratory in Berkeley, by bombarding curium with alpha particles (helium-4 ions).",
    "xpos": 12,
    "ypos": 10
  },
  {
    "name": "Einsteinium",
    "symbol": "Es",
    "number": 99,
    "atomic_mass": 252,
    "category": "actinide",
    "density": 8.84,
    "melt": 1133,
    "boil": 1269,
    "electron_configuration_semantic": "[Rn] 5f11 7s2",
    "summary": "Einsteinium is a synthetic element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide.",
    "xpos": 13,
    "ypos": 10
  },
  {
    "name": "Fermium",
    "symbol": "Fm",
    "number": 100,
    "atomic_mass": 257,
    "category": "actinide",
    "density": null,
    "melt": 1800,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f12 7s2",
    "summary": "Fermium is a synthetic element with symbol Fm and atomic number 100. It is a member of the actinide series.",
    "xpos": 14,
    "ypos": 10
  },
  {
    "name": "Mendelevium",
    "symbol": "Md",
    "number": 101,
    "atomic_mass": 258,
    "category": "actinide",
    "density": null,
    "melt": 1100,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f13 7s2",
    "summary": "Mendelevium is a synthetic element with chemical symbol Md and atomic number 101. A metallic radioactive transuranic element in the actinide series, it is the first element that currently cannot be produced in macroscopic quantities through neutron bombardment of lighter elements.",
    "xpos": 15,
    "ypos": 10
  },
  {
    "name": "Nobelium",
    "symbol": "No",
    "number": 102,
    "atomic_mass": 259,
    "category": "actinide",
    "density": null,
    "melt": 1100,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 7s2",
    "summary": "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science.",
    "xpos": 16,
    "ypos": 10
  },
  {
    "name": "Lawrencium",
    "symbol": "Lr",
    "number": 103,
    "atomic_mass": 266,
    "category": "actinide",
    "density": null,
    "melt": 1900,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 7s2 7p1",
    "summary": "Lawrencium is a synthetic chemical element with chemical symbol Lr and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements.",
    "xpos": 17,
    "ypos": 10
  },
  {
    "name": "Rutherfordium",
    "symbol": "Rf",
    "number": 104,
    "atomic_mass": 267,
    "category": "transition metal",
    "density": 23.2,
    "melt": 2400,
    "boil": 5800,
    "electron_configuration_semantic": "[Rn] 5f14 6d2 7s2",
    "summary": "Rutherfordium is a chemical element with symbol Rf and atomic number 104, named in honor of physicist Ernest Rutherford. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and radioactive; the most stable known isotope, 267Rf, has a half-life of approximately 1.3 hours.",
    "xpos": 4,
    "ypos": 7
  },
  {
    "name": "Dubnium",
    "symbol": "Db",
    "number": 105,
    "atomic_mass": 268,
    "category": "transition metal",
    "density": 29.3,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d3 7s2",
    "summary": "Dubnium is a chemical element with symbol Db and atomic number 105. It is named after the town of Dubna in Russia (then the Soviet Union), where it was first produced.",
    "xpos": 5,
    "ypos": 7
  },
  {
    "name": "Seaborgium",
    "symbol": "Sg",
    "number": 106,
    "atomic_mass": 269,
    "category": "transition metal",
    "density": 35.0,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d4 7s2",
    "summary": "Seaborgium is a synthetic chemical element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn T. Seaborg.",
    "xpos": 6,
    "ypos": 7
  },
  {
    "name": "Bohrium",
    "symbol": "Bh",
    "number": 107,
    "atomic_mass": 270,
    "category": "transition metal",
    "density": 37.1,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d5 7s2",
    "summary": "Bohrium is a chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr.",
    "xpos": 7,
    "ypos": 7
  },
  {
    "name": "Hassium",
    "symbol": "Hs",
    "number": 108,
    "atomic_mass": 269,
    "category": "transition metal",
    "density": 40.7,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d6 7s2",
    "summary": "Hassium is a chemical element with symbol Hs and atomic number 108, named after the German state of Hesse. It is a synthetic element and radioactive; the most stable known isotope, 270Hs, has a half-life of 9 seconds.",
    "xpos": 8,
    "ypos": 7
  },
  {
    "name": "Meitnerium",
    "symbol": "Mt",
    "number": 109,
    "atomic_mass": 278,
    "category": "unknown, probably transition metal",
    "density": 37.4,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d7 7s2",
    "summary": "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is an extremely radioactive synthetic element (an element not found in nature that can be created in a laboratory).",
    "xpos": 9,
    "ypos": 7
  },
  {
    "name": "Darmstadtium",
    "symbol": "Ds",
    "number": 110,
    "atomic_mass": 281,
    "category": "unknown, probably transition metal",
    "density": 34.8,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d8 7s2",
    "summary": "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is an extremely radioactive synthetic element.",
    "xpos": 10,
    "ypos": 7
  },
  {
    "name": "Roentgenium",
    "symbol": "Rg",
    "number": 111,
    "atomic_mass": 282,
    "category": "unknown, probably transition metal",
    "density": 28.7,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d9 7s2",
    "summary": "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is an extremely radioactive synthetic element (an element that can be created in a laboratory but is not found in nature); the most stable known isotope, roentgenium-282, has a half-life of 2.1 minutes.",
    "xpos": 11,
    "ypos": 7
  },
  {
    "name": "Copernicium",
    "symbol": "Cn",
    "number": 112,
    "atomic_mass": 285,
    "category": "transition metal",
    "density": 23.7,
    "melt": null,
    "boil": 357,
    "electron_configuration_semantic": "[Rn] 5f14 6d10 7s2",
    "summary": "Copernicium is a chemical element with symbol Cn and atomic number 112. It is an extremely radioactive synthetic element that can only be created in a laboratory.",
    "xpos": 12,
    "ypos": 7
  },
  {
    "name": "Nihonium",
    "symbol": "Nh",
    "number": 113,
    "atomic_mass": 286,
    "category": "unknown, probably post-transition metal",
    "density": 16,
    "melt": 700,
    "boil": 1400,
    "electron_configuration_semantic": "[Rn] 5f14 6d10 7s2 7p1",
    "summary": "Nihonium is a chemical element with atomic number 113. It has a symbol Nh. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and is extremely radioactive; its most stable known isotope, nihonium-286, has a half-life of 20 seconds.",
    "xpos": 13,
    "ypos": 7
  },
  {
    "name": "Flerovium",
    "symbol": "Fl",
    "number": 114,
    "atomic_mass": 289,
    "category": "post-transition metal",
    "density": 14,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d10 7s2 7p2",
    "summary": "Flerovium is a superheavy artificial chemical element with symbol Fl and atomic number 114. It is an extremely radioactive synthetic element.",
    "xpos": 14,
    "ypos": 7
  },
  {
    "name": "Moscovium",
    "symbol": "Mc",
    "number": 115,
    "atomic_mass": 289,
    "category": "unknown, probably post-transition metal",
    "density": 13.5,
    "melt": 670,
    "boil": 1400,
    "electron_configuration_semantic": "[Rn] 5f14 6d10 7s2 7p3",
    "summary": "Moscovium is a synthetic chemical element with symbol Mc and atomic number 115. It was first synthesized in 2003 by a joint team of Russian and American scientists at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia.",
    "xpos": 15,
    "ypos": 7
  },
  {
    "name": "Livermorium",
    "symbol": "Lv",
    "number": 116,
    "atomic_mass": 293,
    "category": "unknown, probably post-transition metal",
    "density": 12.9,
    "melt": null,
    "boil": null,
    "electron_configuration_semantic": "[Rn] 5f14 6d10 7s2 7p4",
    "summary": "Livermorium is a synthetic superheavy element with symbol Lv and atomic number 116. It is an extremely radioactive element that has only been created in the laboratory and has not been observed in nature.",
    "xpos": 16,
    "ypos": 7
  },
  {
    "name": "Tennessine",
    "symbol": "Ts",
    "number": 117,
    "atomic_mass": 294,
    "category": "unknown, probably metalloid",
    "density": 7.17,
    "melt": null,
    "boil": 883,
    "electron_configuration_semantic": "[Rn] 5f14 6d10 7s2 7p5",
    "summary": "Tennessine is a synthetic chemical element with symbol Ts and atomic number 117. It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table.",
    "xpos": 17,
    "ypos": 7
  },
  {
    "name": "Oganesson",
    "symbol": "Og",
    "number": 118,
    "atomic_mass": 294,
    "category": "unknown, predicted to be noble gas",
    "density": 4.95,
    "melt": null,
    "boil": 350,
    "electron_configuration_semantic": "[Rn] 5f14 6d10 7s2 7p6",
    "summary": "Oganesson is a synthetic chemical element with symbol Og and atomic number 118. It was first synthesized in 2002 at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia, by a joint team of Russian and American scientists.",
    "xpos": 18,
    "ypos": 7
  }
];
